version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network
    

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - "8085:80"
    depends_on:
      - flask
    networks:
      - app-network

  db:
      build:
        context: .
        dockerfile: Dockerfile-postgres
        args:
          - POSTGRES_VERSION=${POSTGRES_VERSION}
      volumes:
        - ./postgres-data:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_DB: students
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
