ARG NGINX_VERSION

FROM nginx:${NGINX_VERSION}

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

LABEL maintainer="Oleg Orlovsky <od.orlovsky@gmail.com>"

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]