ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

WORKDIR /app
COPY ./app /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["wait-for-it", "db:5432", "--", "python", "app.py"]