version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8085:80"
    depends_on:
      - flask
    networks:
      - app-network

  db:
      build:
        context: .
        dockerfile: Dockerfile-postgres
      volumes:
        - ./postgres-data:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_DB: students
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
